/** @noSelfInFile */
// 导出的预载入方法，用来给addon_game_mode.ts调用
export default function Precache(context: CScriptPrecacheContext) {
    // 需要预载的所有资源
    precacheResource(
        [
            // '***.vpcf',
            // 'soundevents/game_sounds_heroes/game_sounds_queenofpain.vsndevts',
            // '***.vmdl',
            'soundevents/custom_sounds.vsndevts',
            'particles/units/heroes/hero_puck/puck_base_attack_warmup.vpcf',
            'particles/units/heroes/hero_faceless_void/faceless_void_time_lock_bash.vpcf',
            'soundevents/game_sounds_heroes/game_sounds_abaddon.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_abyssal_underlord.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_alchemist.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_ancient_apparition.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_antimage.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_arc_warden.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_axe.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_bane.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_batrider.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_beastmaster.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_bloodseeker.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_bounty_hunter.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_brewmaster.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_bristleback.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_broodmother.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_centaur.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_chaos_knight.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_chen.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_clinkz.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_crystalmaiden.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_dark_seer.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_dark_willow.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_dawnbreaker.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_dazzle.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_death_prophet.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_disruptor.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_doombringer.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_dragon_knight.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_drowranger.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_earth_spirit.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_earthshaker.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_elder_titan.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_ember_spirit.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_enchantress.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_enigma.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_faceless_void.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_furion.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_grimstroke.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_gyrocopter.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_hoodwink.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_huskar.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_invoker.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_jakiro.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_juggernaut.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_keeper_of_the_light.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_kunkka.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_legion_commander.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_leshrac.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_lich.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_life_stealer.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_lina.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_lion.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_lone_druid.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_luna.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_lycan.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_magnataur.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_mars.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_marci.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_medusa.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_meepo.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_mirana.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_monkey_king.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_morphling.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_naga_siren.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_necrolyte.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_nevermore.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_nightstalker.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_nyx_assassin.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_obsidian_destroyer.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_ogre_magi.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_omniknight.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_oracle.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_pangolier.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_phantom_assassin.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_phantom_lancer.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_phoenix.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_primal_beast.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_puck.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_pudge.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_pugna.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_queenofpain.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_rattletrap.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_razor.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_riki.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_rubick.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_sandking.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_shadow_demon.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_shadowshaman.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_shredder.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_silencer.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_skeletonking.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_skywrath_mage.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_slardar.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_slark.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_snapfire.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_sniper.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_spectre.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_spirit_breaker.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_stormspirit.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_sven.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_techies.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_templar_assassin.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_terrorblade.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_tidehunter.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_tinker.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_tiny.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_treant.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_troll_warlord.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_tusk.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_undying.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_ursa.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_vengefulspirit.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_venomancer.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_viper.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_visage.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_void_spirit.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_warlock.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_weaver.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_windrunner.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_winter_wyvern.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_wisp.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_witchdoctor.vsndevts',
            'soundevents/game_sounds_heroes/game_sounds_zuus.vsndevts',

            'soundevents/voscripts/game_sounds_vo_abaddon.vsndevts',
            'soundevents/voscripts/game_sounds_vo_abyssal_underlord.vsndevts',
            'soundevents/voscripts/game_sounds_vo_alchemist.vsndevts',
            'soundevents/voscripts/game_sounds_vo_ancient_apparition.vsndevts',
            'soundevents/voscripts/game_sounds_vo_announcer.vsndevts',
            'soundevents/voscripts/game_sounds_vo_announcer_diretide_2012.vsndevts',
            'soundevents/voscripts/game_sounds_vo_announcer_killing_spree.vsndevts',
            'soundevents/voscripts/game_sounds_vo_antimage.vsndevts',
            'soundevents/voscripts/game_sounds_vo_arc_warden.vsndevts',
            'soundevents/voscripts/game_sounds_vo_axe.vsndevts',
            'soundevents/voscripts/game_sounds_vo_bane.vsndevts',
            'soundevents/voscripts/game_sounds_vo_batrider.vsndevts',
            'soundevents/voscripts/game_sounds_vo_beastmaster.vsndevts',
            'soundevents/voscripts/game_sounds_vo_bloodseeker.vsndevts',
            'soundevents/voscripts/game_sounds_vo_bounty_hunter.vsndevts',
            'soundevents/voscripts/game_sounds_vo_brewmaster.vsndevts',
            'soundevents/voscripts/game_sounds_vo_bristleback.vsndevts',
            'soundevents/voscripts/game_sounds_vo_broodmother.vsndevts',
            'soundevents/voscripts/game_sounds_vo_centaur.vsndevts',
            'soundevents/voscripts/game_sounds_vo_chaos_knight.vsndevts',
            'soundevents/voscripts/game_sounds_vo_chen.vsndevts',
            'soundevents/voscripts/game_sounds_vo_clinkz.vsndevts',
            'soundevents/voscripts/game_sounds_vo_crystalmaiden.vsndevts',
            'soundevents/voscripts/game_sounds_vo_dark_seer.vsndevts',
            'soundevents/voscripts/game_sounds_vo_dark_willow.vsndevts',
            'soundevents/voscripts/game_sounds_vo_dawnbreaker.vsndevts',
            'soundevents/voscripts/game_sounds_vo_dazzle.vsndevts',
            'soundevents/voscripts/game_sounds_vo_death_prophet.vsndevts',
            'soundevents/voscripts/game_sounds_vo_disruptor.vsndevts',
            'soundevents/voscripts/game_sounds_vo_doom_bringer.vsndevts',
            'soundevents/voscripts/game_sounds_vo_dragon_knight.vsndevts',
            'soundevents/voscripts/game_sounds_vo_drowranger.vsndevts',
            'soundevents/voscripts/game_sounds_vo_earth_spirit.vsndevts',
            'soundevents/voscripts/game_sounds_vo_earthshaker.vsndevts',
            'soundevents/voscripts/game_sounds_vo_econ_crystal_maiden.vsndevts',
            'soundevents/voscripts/game_sounds_vo_econ_lina.vsndevts',
            'soundevents/voscripts/game_sounds_vo_elder_titan.vsndevts',
            'soundevents/voscripts/game_sounds_vo_ember_spirit.vsndevts',
            'soundevents/voscripts/game_sounds_vo_enchantress.vsndevts',
            'soundevents/voscripts/game_sounds_vo_enigma.vsndevts',
            'soundevents/voscripts/game_sounds_vo_event_ann_dw_morokai.vsndevts',
            'soundevents/voscripts/game_sounds_vo_faceless_void.vsndevts',
            'soundevents/voscripts/game_sounds_vo_furion.vsndevts',
            'soundevents/voscripts/game_sounds_vo_grimstroke.vsndevts',
            'soundevents/voscripts/game_sounds_vo_gyrocopter.vsndevts',
            'soundevents/voscripts/game_sounds_vo_hoodwink.vsndevts',
            'soundevents/voscripts/game_sounds_vo_huskar.vsndevts',
            'soundevents/voscripts/game_sounds_vo_invoker.vsndevts',
            'soundevents/voscripts/game_sounds_vo_jakiro.vsndevts',
            'soundevents/voscripts/game_sounds_vo_juggernaut.vsndevts',
            'soundevents/voscripts/game_sounds_vo_keeper_of_the_light.vsndevts',
            'soundevents/voscripts/game_sounds_vo_kunkka.vsndevts',
            'soundevents/voscripts/game_sounds_vo_legion_commander.vsndevts',
            'soundevents/voscripts/game_sounds_vo_leshrac.vsndevts',
            'soundevents/voscripts/game_sounds_vo_lich.vsndevts',
            'soundevents/voscripts/game_sounds_vo_life_stealer.vsndevts',
            'soundevents/voscripts/game_sounds_vo_lina.vsndevts',
            'soundevents/voscripts/game_sounds_vo_lion.vsndevts',
            'soundevents/voscripts/game_sounds_vo_lone_druid.vsndevts',
            'soundevents/voscripts/game_sounds_vo_luna.vsndevts',
            'soundevents/voscripts/game_sounds_vo_lycan.vsndevts',
            'soundevents/voscripts/game_sounds_vo_magnataur.vsndevts',
            'soundevents/voscripts/game_sounds_vo_mars.vsndevts',
            'soundevents/voscripts/game_sounds_vo_marci.vsndevts',
            'soundevents/voscripts/game_sounds_vo_medusa.vsndevts',
            'soundevents/voscripts/game_sounds_vo_meepo.vsndevts',
            'soundevents/voscripts/game_sounds_vo_mirana.vsndevts',
            'soundevents/voscripts/game_sounds_vo_monkey_king.vsndevts',
            'soundevents/voscripts/game_sounds_vo_morphling.vsndevts',
            'soundevents/voscripts/game_sounds_vo_naga_siren.vsndevts',
            'soundevents/voscripts/game_sounds_vo_necrolyte.vsndevts',
            'soundevents/voscripts/game_sounds_vo_nevermore.vsndevts',
            'soundevents/voscripts/game_sounds_vo_night_stalker.vsndevts',
            'soundevents/voscripts/game_sounds_vo_nyx_assassin.vsndevts',
            'soundevents/voscripts/game_sounds_vo_ogre_magi.vsndevts',
            'soundevents/voscripts/game_sounds_vo_omniknight.vsndevts',
            'soundevents/voscripts/game_sounds_vo_oracle.vsndevts',
            'soundevents/voscripts/game_sounds_vo_outworld_destroyer.vsndevts',
            'soundevents/voscripts/game_sounds_vo_pangolin.vsndevts',
            'soundevents/voscripts/game_sounds_vo_phantom_assassin.vsndevts',
            'soundevents/voscripts/game_sounds_vo_phantom_lancer.vsndevts',
            'soundevents/voscripts/game_sounds_vo_phoenix.vsndevts',
            'soundevents/voscripts/game_sounds_vo_primal_beast.vsndevts',
            'soundevents/voscripts/game_sounds_vo_puck.vsndevts',
            'soundevents/voscripts/game_sounds_vo_pudge.vsndevts',
            'soundevents/voscripts/game_sounds_vo_pugna.vsndevts',
            'soundevents/voscripts/game_sounds_vo_queenofpain.vsndevts',
            'soundevents/voscripts/game_sounds_vo_rattletrap.vsndevts',
            'soundevents/voscripts/game_sounds_vo_razor.vsndevts',
            'soundevents/voscripts/game_sounds_vo_riki.vsndevts',
            'soundevents/voscripts/game_sounds_vo_rubick.vsndevts',
            'soundevents/voscripts/game_sounds_vo_sandking.vsndevts',
            'soundevents/voscripts/game_sounds_vo_secretshop.vsndevts',
            'soundevents/voscripts/game_sounds_vo_shadow_demon.vsndevts',
            'soundevents/voscripts/game_sounds_vo_shadowshaman.vsndevts',
            'soundevents/voscripts/game_sounds_vo_shredder.vsndevts',
            'soundevents/voscripts/game_sounds_vo_silencer.vsndevts',
            'soundevents/voscripts/game_sounds_vo_siltbreaker.vsndevts',
            'soundevents/voscripts/game_sounds_vo_skeleton_king.vsndevts',
            'soundevents/voscripts/game_sounds_vo_skywrath_mage.vsndevts',
            'soundevents/voscripts/game_sounds_vo_slardar.vsndevts',
            'soundevents/voscripts/game_sounds_vo_slark.vsndevts',
            'soundevents/voscripts/game_sounds_vo_snapfire.vsndevts',
            'soundevents/voscripts/game_sounds_vo_sniper.vsndevts',
            'soundevents/voscripts/game_sounds_vo_spectre.vsndevts',
            'soundevents/voscripts/game_sounds_vo_spirit_breaker.vsndevts',
            'soundevents/voscripts/game_sounds_vo_stormspirit.vsndevts',
            'soundevents/voscripts/game_sounds_vo_sven.vsndevts',
            'soundevents/voscripts/game_sounds_vo_sylph.vsndevts',
            'soundevents/voscripts/game_sounds_vo_techies.vsndevts',
            'soundevents/voscripts/game_sounds_vo_templar_assassin.vsndevts',
            'soundevents/voscripts/game_sounds_vo_terrorblade.vsndevts',
            'soundevents/voscripts/game_sounds_vo_tidehunter.vsndevts',
            'soundevents/voscripts/game_sounds_vo_tinker.vsndevts',
            'soundevents/voscripts/game_sounds_vo_tiny.vsndevts',
            'soundevents/voscripts/game_sounds_vo_treant.vsndevts',
            'soundevents/voscripts/game_sounds_vo_troll_warlord.vsndevts',
            'soundevents/voscripts/game_sounds_vo_tusk.vsndevts',
            'soundevents/voscripts/game_sounds_vo_tut1.vsndevts',
            'soundevents/voscripts/game_sounds_vo_undying.vsndevts',
            'soundevents/voscripts/game_sounds_vo_ursa.vsndevts',
            'soundevents/voscripts/game_sounds_vo_vengefulspirit.vsndevts',
            'soundevents/voscripts/game_sounds_vo_venomancer.vsndevts',
            'soundevents/voscripts/game_sounds_vo_viper.vsndevts',
            'soundevents/voscripts/game_sounds_vo_visage.vsndevts',
            'soundevents/voscripts/game_sounds_vo_void_spirit.vsndevts',
            'soundevents/voscripts/game_sounds_vo_warlock.vsndevts',
            'soundevents/voscripts/game_sounds_vo_warlock_golem.vsndevts',
            'soundevents/voscripts/game_sounds_vo_weaver.vsndevts',
            'soundevents/voscripts/game_sounds_vo_windrunner.vsndevts',
            'soundevents/voscripts/game_sounds_vo_winter_wyvern.vsndevts',
            'soundevents/voscripts/game_sounds_vo_wisp.vsndevts',
            'soundevents/voscripts/game_sounds_vo_witchdoctor.vsndevts',
            'soundevents/voscripts/game_sounds_vo_zuus.vsndevts',

            //  kkmusic===============================================
            'sounds/vo/announcer/ann_custom_round_01.vsnd',
            'sounds/vo/announcer/ann_custom_round_02.vsnd',
            'sounds/vo/announcer/ann_custom_round_03.vsnd',
            'sounds/vo/announcer/ann_custom_round_04.vsnd',
            'sounds/vo/announcer/ann_custom_round_05.vsnd',
            'sounds/vo/announcer/ann_custom_round_06.vsnd',
            'sounds/vo/announcer/ann_custom_round_07.vsnd',
            'sounds/vo/announcer/ann_custom_round_08.vsnd',
            'sounds/vo/announcer/ann_custom_round_09.vsnd',
            'sounds/vo/announcer/ann_custom_round_10.vsnd',
            'sounds/vo/announcer/ann_custom_round_begin_01.vsnd',
            'sounds/weapons/hero/primal_beast/ground_pound.vsnd',
        ],
        context
    );
    // 需要预载入的kv文件，会自动解析KV文件中的所有vpcf资源等等
    precacheEveryResourceInKV(
        [
            // kv文件路径
            // 'npc_abilities_custom.txt',
        ],
        context
    );
    // 需要预载入的单位
    precacheUnits(
        [
            // "npc_dota_hero_ancient_apparition",
            // "npc_dota_hero_antimage",
            // "npc_dota_hero_axe",
            // "npc_dota_hero_bane",
            // "npc_dota_hero_beastmaster",
            // "npc_dota_hero_bloodseeker",
            // "npc_dota_hero_chen",
            // "npc_dota_hero_crystal_maiden",
            // "npc_dota_hero_dark_seer",
            // "npc_dota_hero_dazzle",
            // "npc_dota_hero_dragon_knight",
            // "npc_dota_hero_doom_bringer",
            // "npc_dota_hero_drow_ranger",
            // "npc_dota_hero_earthshaker",
            // "npc_dota_hero_enchantress",
            // "npc_dota_hero_enigma",
            // "npc_dota_hero_faceless_void",
            // "npc_dota_hero_furion",
            // "npc_dota_hero_juggernaut",
            // "npc_dota_hero_kunkka",
            // "npc_dota_hero_leshrac",
            // "npc_dota_hero_lich",
            // "npc_dota_hero_life_stealer",
            // "npc_dota_hero_lina",
            // "npc_dota_hero_lion",
            // "npc_dota_hero_mirana",
            // "npc_dota_hero_morphling",
            // "npc_dota_hero_necrolyte",
            // "npc_dota_hero_nevermore",
            // "npc_dota_hero_night_stalker",
            // "npc_dota_hero_omniknight",
            // "npc_dota_hero_puck",
            // "npc_dota_hero_pudge",
            // "npc_dota_hero_pugna",
            // "npc_dota_hero_rattletrap",
            // "npc_dota_hero_razor",
            // "npc_dota_hero_riki",
            // "npc_dota_hero_sand_king",
            // "npc_dota_hero_shadow_shaman",
            // "npc_dota_hero_slardar",
            // "npc_dota_hero_sniper",
            // "npc_dota_hero_spectre",
            // "npc_dota_hero_storm_spirit",
            // "npc_dota_hero_sven",
            // "npc_dota_hero_tidehunter",
            // "npc_dota_hero_tinker",
            // "npc_dota_hero_tiny",
            // "npc_dota_hero_vengefulspirit",
            // "npc_dota_hero_venomancer",
            // "npc_dota_hero_viper",
            // "npc_dota_hero_weaver",
            // "npc_dota_hero_windrunner",
            // "npc_dota_hero_witch_doctor",
            // "npc_dota_hero_zuus",
            // "npc_dota_hero_broodmother",
            // "npc_dota_hero_skeleton_king",
            // "npc_dota_hero_queenofpain",
            // "npc_dota_hero_huskar",
            // "npc_dota_hero_jakiro",
            // "npc_dota_hero_batrider",
            // "npc_dota_hero_warlock",
            // "npc_dota_hero_alchemist",
            // "npc_dota_hero_death_prophet",
            // "npc_dota_hero_ursa",
            // "npc_dota_hero_bounty_hunter",
            // "npc_dota_hero_silencer",
            // "npc_dota_hero_spirit_breaker",
            // "npc_dota_hero_invoker",
            // "npc_dota_hero_clinkz",
            // "npc_dota_hero_obsidian_destroyer",
            // "npc_dota_hero_shadow_demon",
            // "npc_dota_hero_lycan",
            // "npc_dota_hero_lone_druid",
            // "npc_dota_hero_brewmaster",
            // "npc_dota_hero_phantom_lancer",
            // "npc_dota_hero_treant",
            // "npc_dota_hero_ogre_magi",
            // "npc_dota_hero_chaos_knight",
            // "npc_dota_hero_phantom_assassin",
            // "npc_dota_hero_gyrocopter",
            // "npc_dota_hero_rubick",
            // "npc_dota_hero_luna",
            // "npc_dota_hero_wisp",
            // "npc_dota_hero_disruptor",
            // "npc_dota_hero_undying",
            // "npc_dota_hero_templar_assassin",
            // "npc_dota_hero_naga_siren",
            // "npc_dota_hero_nyx_assassin",
            // "npc_dota_hero_keeper_of_the_light",
            // "npc_dota_hero_visage",
            // "npc_dota_hero_meepo",
            // "npc_dota_hero_magnataur",
            // "npc_dota_hero_centaur",
            // "npc_dota_hero_slark",
            // "npc_dota_hero_shredder",
            // "npc_dota_hero_medusa",
            // "npc_dota_hero_troll_warlord",
            // "npc_dota_hero_tusk",
            // "npc_dota_hero_bristleback",
            // "npc_dota_hero_skywrath_mage",
            // "npc_dota_hero_elder_titan",
            // "npc_dota_hero_abaddon",
            // "npc_dota_hero_earth_spirit",
            // "npc_dota_hero_ember_spirit",
            // "npc_dota_hero_legion_commander",
            // "npc_dota_hero_phoenix",
            // "npc_dota_hero_terrorblade",
            // "npc_dota_hero_techies",
            // "npc_dota_hero_oracle",
            // "npc_dota_hero_winter_wyvern",
            // "npc_dota_hero_arc_warden",
            // "npc_dota_hero_abyssal_underlord",
            // "npc_dota_hero_monkey_king",
            // "npc_dota_hero_dark_willow",
            // "npc_dota_hero_pangolier",
            // "npc_dota_hero_grimstroke",
            // "npc_dota_hero_mars",
            // "npc_dota_hero_snapfire",
            // "npc_dota_hero_void_spirit",

            // 单位名称
            'npc_kv_test',
            'npc_master_001',
            'npc_teleporter',

            // 'npc_dota_hero_***',
            // "npc_td_tower_001_1",
            // "npc_td_tower_001_2",
            // "npc_td_tower_002_1",
            // "npc_td_tower_002_2",
            // "npc_td_tower_002_3",
            // "npc_td_tower_002_4",
            // "npc_td_tower_003_1",
            // "npc_td_tower_003_2",
            // "npc_td_tower_003_3",
            // "npc_td_tower_003_4",
            // "npc_td_tower_004_1",
            // "npc_td_tower_004_2",
            // "npc_td_tower_004_3",
            // "npc_td_tower_004_4",
            // "npc_td_tower_005_1",
            // "npc_td_tower_005_2",
            // "npc_td_tower_005_3",
            // "npc_td_tower_006_1",
            // "npc_td_tower_006_2",
            // "npc_td_tower_006_3",
            // "npc_td_tower_006_4",
            // "npc_td_tower_007_1",
            // "npc_td_tower_007_3",
            // "npc_td_tower_007_4",
            // "npc_td_tower_008_1",
            // "npc_td_tower_008_2",
            // "npc_td_tower_008_3",
            // "npc_td_tower_009_1",
            // "npc_td_tower_009_2",
            // "npc_td_tower_009_3",
            // "npc_td_tower_010_1",
            // "npc_td_tower_010_2",
            // "npc_td_tower_010_3",
            // "npc_td_tower_011_1",
            // "npc_td_tower_011_2",
            // "npc_td_tower_011_3",
            // "npc_td_tower_011_4",
            // "npc_td_tower_012_1",
            // "npc_td_tower_013_1",
            // "npc_td_tower_014_1",
            // "npc_td_tower_015_1",
            // "npc_td_tower_016_1",
            // "npc_td_tower_017_1",
            // "npc_td_tower_018_1",
            // "npc_td_tower_019_1",
            // "npc_td_tower_020_1",
            // "npc_td_tower_021_1",
            // "npc_td_tower_022_1",
            // "npc_td_tower_022_2",
            // "npc_td_tower_022_3",
            // "npc_td_tower_022_4",
            // "npc_td_tower_023_1",
            // "npc_td_tower_023_2",
            // "npc_td_tower_023_3",
            // "npc_td_tower_023_4",
            // "npc_td_tower_024_1",
            // "npc_td_tower_024_2",
            // "npc_td_tower_024_3",
            // "npc_td_tower_024_4",
            // "npc_td_tower_025_1",
            // "npc_td_tower_025_2",
            // "npc_td_tower_025_3",
            // "npc_td_tower_025_4",
            // "npc_td_tower_026_1",
            // "npc_td_tower_026_2",
            // "npc_td_tower_026_3",
            // "npc_td_tower_026_4",
            // "npc_td_tower_027_1",
            // "npc_td_tower_027_2",
            // "npc_td_tower_027_3",
            // "npc_td_tower_028_1",
            // "npc_td_tower_028_2",
            // "npc_td_tower_028_3",
            // "npc_td_tower_028_4",
            // "npc_td_tower_029_1",
            // "npc_td_tower_029_2",
            // "npc_td_tower_029_3",
            // "npc_td_tower_029_4",
            // "npc_td_tower_030_1",
            // "npc_td_tower_030_2",
            // "npc_td_tower_030_3",
            // "npc_td_tower_030_4",
            // "npc_td_tower_031_1",
            // "npc_td_tower_031_2",
            // "npc_td_tower_031_3",
            // "npc_td_tower_031_4",
            // "npc_td_tower_032_1",
            // "npc_td_tower_032_2",
            // "npc_td_tower_032_3",
            // "npc_td_tower_032_4",
            // "npc_td_tower_033_1",
            // "npc_td_tower_033_2",
            // "npc_td_tower_033_3",
            // "npc_td_tower_033_4",
            // "npc_td_tower_034_1",
            // "npc_td_tower_034_2",
            // "npc_td_tower_034_3",
            // "npc_td_tower_034_4",
            // "npc_td_tower_035_1",
            // "npc_td_tower_035_2",
            // "npc_td_tower_035_3",
            // "npc_td_tower_035_4",
            // "npc_td_tower_036_1",
            // "npc_td_tower_036_2",
            // "npc_td_tower_036_3",
            // "npc_td_tower_036_4",
            // "npc_td_tower_037_1",
            // "npc_td_tower_037_2",
            // "npc_td_tower_037_3",
            // "npc_td_tower_037_4",
            // "npc_td_tower_038_1",
            // "npc_td_tower_038_2",
            // "npc_td_tower_038_3",
            // "npc_td_tower_038_4",
            // "npc_td_tower_039_1",
            // "npc_td_tower_039_2",
            // "npc_td_tower_039_3",
            // "npc_td_tower_039_4",
            // "npc_td_tower_040_1",
            // "npc_td_tower_040_2",
            // "npc_td_tower_040_3",
            // "npc_td_tower_040_4",
            // "npc_td_tower_041_1",
            // "npc_td_tower_041_2",
            // "npc_td_tower_041_3",
            // "npc_td_tower_042_1",
            // "npc_td_tower_042_2",
            // "npc_td_tower_042_3",
            // "npc_td_tower_042_4",
            // "npc_td_tower_043_1",
            // "npc_td_tower_043_2",
            // "npc_td_tower_043_3",
            // "npc_td_tower_043_4",
            // "npc_td_tower_044_1",
            // "npc_td_tower_044_2",
            // "npc_td_tower_044_3",
            // "npc_td_tower_044_4",
            // "npc_td_tower_045_1",
            // "npc_td_tower_045_2",
            // "npc_td_tower_045_3",
            // "npc_td_tower_045_4",
            // "npc_td_tower_046_1",
            // "npc_td_tower_046_2",
            // "npc_td_tower_046_3",
            // "npc_td_tower_046_4",
            // "npc_td_tower_047_1",
            // "npc_td_tower_047_2",
            // "npc_td_tower_047_3",
            // "npc_td_tower_047_4",
            // "npc_td_tower_048_1",
            // "npc_td_tower_048_2",
            // "npc_td_tower_048_3",
            // "npc_td_tower_048_4",
            // "npc_td_tower_049_1",
            // "npc_td_tower_049_2",
            // "npc_td_tower_049_3",
            // "npc_td_tower_049_4",
            // "npc_td_tower_050_1",
            // "npc_td_tower_050_2",
            // "npc_td_tower_050_3",
            // "npc_td_tower_050_4",
            // "npc_td_tower_051_1",
            // "npc_td_tower_051_2",
            // "npc_td_tower_051_3",
            // "npc_td_tower_051_4",
            // "npc_td_tower_052_1",
            // "npc_td_tower_052_2",
            // "npc_td_tower_052_3",
            // "npc_td_tower_052_4",
            // "npc_td_tower_053_1",
            // "npc_td_tower_053_2",
            // "npc_td_tower_053_3",
            // "npc_td_tower_053_4",
            // "npc_td_tower_054_1",
            // "npc_td_tower_054_2",
            // "npc_td_tower_054_3",
            // "npc_td_tower_054_4",
            // "npc_td_tower_055_1",
            // "npc_td_tower_055_2",
            // "npc_td_tower_055_3",
            // "npc_td_tower_055_4",
            // "npc_td_tower_056_1",
            // "npc_td_tower_056_2",
            // "npc_td_tower_056_3",
            // "npc_td_tower_056_4",
            // "npc_td_tower_057_1",
            // "npc_td_tower_057_2",
            // "npc_td_tower_057_3",
            // "npc_td_tower_057_4",
            // "npc_td_tower_058_1",
            // "npc_td_tower_058_2",
            // "npc_td_tower_058_3",
            // "npc_td_tower_058_4",
            // "npc_td_tower_059_1",
            // "npc_td_tower_059_2",
            // "npc_td_tower_059_3",
            // "npc_td_tower_059_4",
            // "npc_td_tower_060_1",
            // "npc_td_tower_060_2",
            // "npc_td_tower_060_3",
            // "npc_td_tower_060_4",
            // "npc_td_tower_061_1",
            // "npc_td_tower_061_2",
            // "npc_td_tower_061_3",
            // "npc_td_tower_061_4",
            // "npc_td_tower_062_1",
            // "npc_td_tower_062_2",
            // "npc_td_tower_062_3",
            // "npc_td_tower_062_4",
            // "npc_td_tower_063_1",
            // "npc_td_tower_063_2",
            // "npc_td_tower_063_3",
            // "npc_td_tower_063_4",
            // "npc_td_tower_064_1",
            // "npc_td_tower_064_2",
            // "npc_td_tower_064_3",
            // "npc_td_tower_064_4",
            // "npc_td_tower_065_1",
            // "npc_td_tower_065_2",
            // "npc_td_tower_065_3",
            // "npc_td_tower_065_4",
            // "npc_td_tower_066_1",
            // "npc_td_tower_066_2",
            // "npc_td_tower_066_3",
            // "npc_td_tower_066_4",
            // "npc_td_tower_067_1",
            // "npc_td_tower_067_2",
            // "npc_td_tower_067_3",
            // "npc_td_tower_067_4",
            // "npc_td_tower_068_1",
            // "npc_td_tower_068_2",
            // "npc_td_tower_068_3",
            // "npc_td_tower_068_4",
            // "npc_td_tower_069_1",
            // "npc_td_tower_069_2",
            // "npc_td_tower_069_3",
            // "npc_td_tower_069_4",
            // "npc_td_tower_070_1",
            // "npc_td_tower_070_2",
            // "npc_td_tower_070_3",
            // "npc_td_tower_070_4",
            // "npc_td_tower_071_1",
            // "npc_td_tower_071_2",
            // "npc_td_tower_071_3",
            // "npc_td_tower_071_4",
            // "npc_td_tower_072_1",
            // "npc_td_tower_072_2",
            // "npc_td_tower_072_3",
            // "npc_td_tower_072_4",
            // "npc_td_tower_073_1",
            // "npc_td_tower_073_2",
            // "npc_td_tower_073_3",
            // "npc_td_tower_073_4",
            // "npc_td_tower_074_1",
            // "npc_td_tower_074_2",
            // "npc_td_tower_074_3",
            // "npc_td_tower_074_4",
            // "npc_td_tower_075_1",
            // "npc_td_tower_075_2",
            // "npc_td_tower_075_3",
            // "npc_td_tower_075_4",
            // "npc_td_tower_076_1",
            // "npc_td_tower_076_2",
            // "npc_td_tower_076_3",
            // "npc_td_tower_076_4",
            // "npc_td_tower_077_1",
            // "npc_td_tower_077_2",
            // "npc_td_tower_077_3",
            // "npc_td_tower_077_4",
            // "npc_td_tower_078_1",
            // "npc_td_tower_078_2",
            // "npc_td_tower_078_3",
            // "npc_td_tower_078_4",
            // "npc_td_tower_079_1",
            // "npc_td_tower_079_2",
            // "npc_td_tower_079_3",
            // "npc_td_tower_079_4",
            // "npc_td_tower_080_1",
            // "npc_td_tower_080_2",
            // "npc_td_tower_080_3",
            // "npc_td_tower_080_4",
            // "npc_td_tower_081_1",
            // "npc_td_tower_081_2",
            // "npc_td_tower_081_3",
            // "npc_td_tower_081_4",
            // "npc_td_tower_082_1",
            // "npc_td_tower_082_2",
            // "npc_td_tower_082_3",
            // "npc_td_tower_082_4",
            // "npc_td_tower_083_1",
            // "npc_td_tower_083_2",
            // "npc_td_tower_083_3",
            // "npc_td_tower_083_4",
            // "npc_td_tower_084_1",
            // "npc_td_tower_084_2",
            // "npc_td_tower_084_3",
            // "npc_td_tower_084_4",
            // "npc_td_tower_085_1",
            // "npc_td_tower_085_2",
            // "npc_td_tower_085_3",
            // "npc_td_tower_085_4",
            // "npc_td_tower_086_1",
            // "npc_td_tower_086_2",
            // "npc_td_tower_086_3",
            // "npc_td_tower_086_4",
            // "npc_td_tower_087_1",
            // "npc_td_tower_087_2",
            // "npc_td_tower_087_3",
            // "npc_td_tower_087_4",
            // "npc_td_tower_088_1",
            // "npc_td_tower_088_2",
            // "npc_td_tower_088_3",
            // "npc_td_tower_088_4",
            // "npc_td_tower_089_1",
            // "npc_td_tower_089_2",
            // "npc_td_tower_089_3",
            // "npc_td_tower_089_4",
            // "npc_td_tower_090_1",
            // "npc_td_tower_090_2",
            // "npc_td_tower_090_3",
            // "npc_td_tower_090_4",
            // "npc_td_tower_091_1",
            // "npc_td_tower_091_2",
            // "npc_td_tower_091_3",
            // "npc_td_tower_091_4",
            // "npc_td_tower_092_1",
            // "npc_td_tower_092_2",
            // "npc_td_tower_092_3",
            // "npc_td_tower_092_4",
            // "npc_td_tower_093_1",
            // "npc_td_tower_093_2",
            // "npc_td_tower_093_3",
            // "npc_td_tower_093_4",
            // "npc_td_tower_094_1",
            // "npc_td_tower_094_2",
            // "npc_td_tower_094_3",
            // "npc_td_tower_094_4",
            // "npc_td_tower_095_1",
            // "npc_td_tower_095_2",
            // "npc_td_tower_095_3",
            // "npc_td_tower_095_4",
            // "npc_td_tower_096_1",
            // "npc_td_tower_096_2",
            // "npc_td_tower_096_3",
            // "npc_td_tower_096_4",
            // "npc_td_tower_097_1",
            // "npc_td_tower_097_2",
            // "npc_td_tower_097_3",
            // "npc_td_tower_097_4",
            // "npc_td_tower_098_1",
            // "npc_td_tower_098_2",
            // "npc_td_tower_098_3",
            // "npc_td_tower_098_4",
            // "npc_td_tower_099_1",
            // "npc_td_tower_099_2",
            // "npc_td_tower_099_3",
            // "npc_td_tower_099_4",
            // "npc_td_tower_100_1",
            // "npc_td_tower_100_2",
            // "npc_td_tower_100_3",
            // "npc_td_tower_100_4",
            // "npc_td_tower_101_1",
            // "npc_td_tower_101_2",
            // "npc_td_tower_101_3",
            // "npc_td_tower_101_4",
            // "npc_td_tower_102_1",
            // "npc_td_tower_102_2",
            // "npc_td_tower_102_3",
            // "npc_td_tower_102_4",
            // "npc_td_tower_103_1",
            // "npc_td_tower_103_2",
            // "npc_td_tower_103_3",
            // "npc_td_tower_103_4",
            // "npc_td_tower_104_1",
            // "npc_td_tower_104_2",
            // "npc_td_tower_104_3",
            // "npc_td_tower_104_4",
            // "npc_td_tower_105_1",
            // "npc_td_tower_105_2",
            // "npc_td_tower_105_3",
            // "npc_td_tower_105_4",
            // "npc_td_tower_106_1",
            // "npc_td_tower_106_2",
            // "npc_td_tower_106_3",
            // "npc_td_tower_106_4",
            // "npc_td_tower_107_1",
            // "npc_td_tower_107_2",
            // "npc_td_tower_107_3",
            // "npc_td_tower_107_4",
            // "npc_td_tower_108_1",
            // "npc_td_tower_108_2",
            // "npc_td_tower_108_3",
            // "npc_td_tower_108_4",
            // "npc_td_tower_109_1",
            // "npc_td_tower_109_2",
            // "npc_td_tower_109_3",
            // "npc_td_tower_109_4",
            // "npc_td_tower_110_1",
            // "npc_td_tower_110_2",
            // "npc_td_tower_110_3",
            // "npc_td_tower_110_4",
            // "npc_td_tower_111_1",
            // "npc_td_tower_111_2",
            // "npc_td_tower_111_3",
            // "npc_td_tower_111_4",
            // "npc_td_tower_112_1",
            // "npc_td_tower_112_1",
            // "npc_td_tower_112_1",
            // "npc_td_tower_112_1",
            // "npc_td_tower_113_1",
            // "npc_td_tower_113_2",
            // "npc_td_tower_113_3",
            // "npc_td_tower_113_4",
            // "npc_td_tower_114_1",
            // "npc_td_tower_114_2",
            // "npc_td_tower_114_3",
            // "npc_td_tower_114_4",
            // "npc_td_tower_115_1",
            // "npc_td_tower_115_2",
            // "npc_td_tower_115_3",
            // "npc_td_tower_115_4",
            // "npc_td_tower_116_1",
            // "npc_td_tower_116_2",
            // "npc_td_tower_116_3",
            // "npc_td_tower_116_4",
            // "npc_td_tower_117_1",
            // "npc_td_tower_117_2",
            // "npc_td_tower_117_3",
            // "npc_td_tower_117_4",
            // "npc_td_tower_118_1",
            // "npc_td_tower_118_2",
            // "npc_td_tower_118_3",
            // "npc_td_tower_118_4",
            // "npc_td_tower_119_1",
            // "npc_td_tower_119_2",
            // "npc_td_tower_119_3",
            // "npc_td_tower_119_4",
            // "npc_td_tower_120_1",
            // "npc_td_tower_120_2",
            // "npc_td_tower_120_3",
            // "npc_td_tower_120_4",
            // "npc_td_tower_121_1",
            // "npc_td_tower_121_2",
            // "npc_td_tower_121_3",
            // "npc_td_tower_121_4",
            // "npc_td_tower_122_1",
            // "npc_td_tower_122_2",
            // "npc_td_tower_122_3",
            // "npc_td_tower_122_4",
            // "npc_td_tower_123_1",
            // "npc_td_tower_123_2",
            // "npc_td_tower_123_3",
            // "npc_td_tower_123_4",
            // "npc_td_tower_124_1",
            // "npc_td_tower_124_2",
            // "npc_td_tower_124_3",
            // "npc_td_tower_124_4",
            // "npc_td_tower_125_1",
            // "npc_td_tower_125_2",
            // "npc_td_tower_125_3",
            // "npc_td_tower_125_4",
            // "npc_td_tower_126_1",
            // "npc_td_tower_126_2",
            // "npc_td_tower_126_3",
            // "npc_td_tower_127_1",
            // "npc_td_tower_127_2",
            // "npc_td_tower_127_3",
            // "npc_td_tower_127_4",
            // "npc_td_tower_128_1",
            // "npc_td_tower_128_2",
            // "npc_td_tower_128_3",
            // "npc_td_tower_128_4",
            // "npc_td_tower_129_1",
            // "npc_td_tower_129_2",
            // "npc_td_tower_129_3",
            // "npc_td_tower_129_4",
            // "npc_td_tower_130_1",
            // "npc_td_tower_130_2",
            // "npc_td_tower_130_3",
            // "npc_td_tower_130_4",
            // "npc_td_tower_131_1",
            // "npc_td_tower_131_2",
            // "npc_td_tower_131_3",
            // "npc_td_tower_131_4",
            // "npc_td_tower_132_1",
            // "npc_td_tower_132_2",
            // "npc_td_tower_132_3",
            // "npc_td_tower_132_4",
            // "npc_td_tower_133_1",
            // "npc_td_tower_133_2",
            // "npc_td_tower_133_3",
            // "npc_td_tower_133_4",
            // "npc_td_tower_134_1",
            // "npc_td_tower_134_2",
            // "npc_td_tower_135_1",
            // "npc_td_tower_135_2",
            // "npc_td_tower_135_3",
            // "npc_td_tower_136_1",
            // "npc_td_tower_136_2",
            // "npc_td_tower_136_3",
            // "npc_td_tower_136_4",
            // "npc_td_tower_137_1",
            // "npc_td_tower_137_2",
            // "npc_td_tower_137_3",
            // "npc_td_tower_137_4",
            // "npc_td_tower_138_1",
            // "npc_td_tower_138_2",
            // "npc_td_tower_138_3",
            // "npc_td_tower_138_4",
            // "npc_td_tower_139_1",
            // "npc_td_tower_139_2",
            // "npc_td_tower_139_3",
            // "npc_td_tower_139_4",
            // "npc_td_tower_140_1",
            // "npc_td_tower_140_2",
            // "npc_td_tower_140_3",
            // "npc_td_tower_140_4",
            // "npc_td_tower_141_1",
            // "npc_td_tower_141_2",
            // "npc_td_tower_141_3",
            // "npc_td_tower_141_4",
            // "npc_td_tower_142_1",
            // "npc_td_tower_142_2",
            // "npc_td_tower_142_3",
            // "npc_td_tower_142_4",
            // "npc_td_tower_143_1",
            // "npc_td_tower_143_2",
            // "npc_td_tower_143_3",
            // "npc_td_tower_143_4",
            // "npc_td_tower_901_1",
            // "npc_td_tower_901_2",
            // "npc_td_tower_901_3",
            // "npc_td_tower_902_1",
            // "npc_td_tower_902_2",
            // "npc_td_tower_902_3",
        ],
        context
    );
    // 需要预载入的物品
    precacheItems(
        [
            // 物品名称
            // 'item_***',
        ],
        context
    );
    print(`[Precache] Precache finished.`);
}

// 预载入KV文件中的所有资源
function precacheEveryResourceInKV(kvFileList: string[], context: CScriptPrecacheContext) {
    kvFileList.forEach(file => {
        const kvTable = LoadKeyValues(file);
        precacheEverythingFromTable(kvTable, context);
    });
}
// 预载入资源列表
function precacheResource(resourceList: string[], context: CScriptPrecacheContext) {
    resourceList.forEach(resource => {
        precacheResString(resource, context);
    });
}
function precacheResString(res: string, context: CScriptPrecacheContext) {
    if (res.endsWith('.vpcf')) {
        PrecacheResource('particle', res, context);
    } else if (res.endsWith('.vsndevts')) {
        PrecacheResource('soundfile', res, context);
    } else if (res.endsWith('.vmdl')) {
        PrecacheResource('model', res, context);
    }
}

// 预载入单位列表
function precacheUnits(unitNamesList: string[], context?: CScriptPrecacheContext) {
    if (context != null) {
        unitNamesList.forEach(unitName => {
            PrecacheUnitByNameSync(unitName, context);
        });
    } else {
        unitNamesList.forEach(unitName => {
            PrecacheUnitByNameAsync(unitName, () => {});
        });
    }
}
// 预载入物品列表
function precacheItems(itemList: string[], context: CScriptPrecacheContext) {
    itemList.forEach(itemName => {
        PrecacheItemByNameSync(itemName, context);
    });
}

// 一个辅助的，从KV表中解析出所有资源并预载入的方法
function precacheEverythingFromTable(kvTable: any, context: CScriptPrecacheContext) {
    for (const [k, v] of pairs(kvTable)) {
        if (type(v) === 'table') {
            precacheEverythingFromTable(v, context);
        } else if (type(v) === 'string') {
            precacheResString(v, context);
        }
    }
}
